from node_editor.node.mol_descriptors.functions import *

# Code / Description / Main function

# Constitutional descriptors: composition
desc_composition = {
    "aMW": ["Average molecular weight", MW('a')],
    "eMW": ["Exact molecular weight", MW('e')],
    "nAtom": ["Number of atoms", AtomCount('Atom')],
    "nhAtom": ["Number of non-hydrogen atoms", AtomCount('HeavyAtom')],
    "nHAtoms": ["Number of heteroatoms", AtomCount('Hetero')],
    "nH": ["Number of H atoms", AtomCount('H')],
    "nB": ["Number of B atoms", AtomCount('B')],
    "nC": ["Number of C atoms", AtomCount('C')],
    "nN": ["Number of N atoms", AtomCount('N')],
    "nO": ["Number of O atoms", AtomCount('O')],
    "nS": ["Number of S atoms", AtomCount('S')],
    "nP": ["Number of P atoms", AtomCount('P')],
    "nF": ["Number of F atoms", AtomCount('F')],
    "nCl": ["Number of Cl atoms", AtomCount('Cl')],
    "nBr": ["Number of Br atoms", AtomCount('Br')],
    "nI": ["Number of I atoms", AtomCount('I')],
    "nX": ["Number of halogen atoms", AtomCount('X')],
    "nNHOH": ["Number of NHs or OHs", AtomCount('NHOH')],
    "nNO": ["Number of N and O atoms", AtomCount('NO')],
    "nHdonors": ["Number of hydrogen bond donors", AtomCount('Hdonnors')],
    "nHacceptors": ["Number of hydrogen bond acceptors", AtomCount('Hacceptors')],
    "nValelec": ["Number of valence electrons", ElecCount('Valence')],
    "nRadielec": ["Number of radical electrons", ElecCount('Radical')],
}

# Topological descriptors: connectivity
# desc_connectivity = {
#     "nBonds": ["Number of bonds", Calculator(BondCount.BondCount('any', False)), None],
#     "nBondsO": ["Number of bonds between heavy atoms", Calculator(BondCount.BondCount('heavy', False)), None],
#     "nBondsS": ["Number of single bonds", Calculator(BondCount.BondCount('single', False)), None],
#     "nBondsD": ["Number of double bonds", Calculator(BondCount.BondCount('double', False)), None],
#     "nBondsT": ["Number of triple bonds", Calculator(BondCount.BondCount('triple', False)), None],
#     "nBondsM": ["Number of multiple bonds", Calculator(BondCount.BondCount('multiple', False)), None],
#     "nBondsKS": ["Number of single bonds in kekulized strucutre", Calculator(BondCount.BondCount('single', True)), None],
#     "nBondsKD": ["Number of double bonds in kekulized structure", Calculator(BondCount.BondCount('double', True)), None],
#     "nRots": ["Number of rotatable bonds", rdMolDescriptors.CalcNumRotatableBonds, Calculator(RotatableBond.RotatableBondsCount)],
#     "nRotRatio": ["Rotatable bonds ratio", Calculator(RotatableBond.RotatableBondsRatio), None],
#     "nAmides": ["Number of amide bonds", rdMolDescriptors.CalcNumAmideBonds, None],
#     "nArAtoms": ["Number of aromatic atoms", Calculator(Aromatic.AromaticAtomsCount), None],
#     "nArBonds": ["Number of aromatic bonds", Calculator(Aromatic.AromaticBondsCount), Calculator(BondCount.BondCount('aromatic', False))],
#     "nSAtoms": ["Number of spiro atoms", rdMolDescriptors.CalcNumSpiroAtoms, Calculator(AtomCount.AtomCount('Spiro'))],
#     "nBAtoms": ["Number of bridgehead atoms", rdMolDescriptors.CalcNumBridgeheadAtoms, Calculator(AtomCount.AtomCount('Bridgehead'))],
    
#     "nRings": ["Number of rings", Lipinski.RingCount, Calculator(RingCount.RingCount(None,False,False,None,None))],
#     "n3Rings": ["Number of 3-membered rings", Calculator(RingCount.RingCount(3,False,False,None,None)), None],
#     "n4Rings": ["Number of 4-membered rings", Calculator(RingCount.RingCount(4,False,False,None,None)), None],
#     "n5Rings": ["Number of 5-membered rings", Calculator(RingCount.RingCount(5,False,False,None,None)), None],
#     "n6Rings": ["Number of 5-membered rings", Calculator(RingCount.RingCount(6,False,False,None,None)), None],
#     "n7Rings": ["Number of 5-membered rings", Calculator(RingCount.RingCount(7,False,False,None,None)), None],
#     "n8Rings": ["Number of 5-membered rings", Calculator(RingCount.RingCount(8,False,False,None,None)), None],
#     "n9Rings": ["Number of 5-membered rings", Calculator(RingCount.RingCount(9,False,False,None,None)), None],
#     "n10Rings": ["Number of 5-membered rings", Calculator(RingCount.RingCount(10,False,False,None,None)), None],
#     "n11Rings": ["Number of 5-membered rings", Calculator(RingCount.RingCount(11,False,False,None,None)), None],
#     "n12Rings": ["Number of 5-membered rings", Calculator(RingCount.RingCount(12,False,False,None,None)), None],
#     "nG3Rings": ["Number of rings with 3 or more atoms", Calculator(RingCount.RingCount(3,True,False,None,None)), None],
#     "nG4Rings": ["Number of rings with 4 or more atoms", Calculator(RingCount.RingCount(4,True,False,None,None)), None],
#     "nG5Rings": ["Number of rings with 5 or more atoms", Calculator(RingCount.RingCount(5,True,False,None,None)), None],
#     "nG6Rings": ["Number of rings with 6 or more atoms", Calculator(RingCount.RingCount(6,True,False,None,None)), None],
#     "nG7Rings": ["Number of rings with 7 or more atoms", Calculator(RingCount.RingCount(7,True,False,None,None)), None],
#     "nG8Rings": ["Number of rings with 8 or more atoms", Calculator(RingCount.RingCount(8,True,False,None,None)), None],
#     "nG9Rings": ["Number of rings with 9 or more atoms", Calculator(RingCount.RingCount(9,True,False,None,None)), None],
#     "nG10Rings": ["Number of rings with 10 or more atoms", Calculator(RingCount.RingCount(10,True,False,None,None)), None],
#     "nG11Rings": ["Number of rings with 11 or more atoms", Calculator(RingCount.RingCount(11,True,False,None,None)), None],
#     "nG12Rings": ["Number of rings with 12 or more atoms", Calculator(RingCount.RingCount(12,True,False,None,None)), None],
#     "nHRings": ["Number of hetero rings", Calculator(RingCount.RingCount(None,False,False,None,True)), None],
#     "n3HRings": ["Number of hetero 3-membered rings", Calculator(RingCount.RingCount(3,False,False,None,True)), None],
#     "n4HRings": ["Number of hetero 4-membered rings", Calculator(RingCount.RingCount(4,False,False,None,True)), None],
#     "n5HRings": ["Number of hetero 5-membered rings", Calculator(RingCount.RingCount(5,False,False,None,True)), None],
#     "n6HRings": ["Number of hetero 6-membered rings", Calculator(RingCount.RingCount(6,False,False,None,True)), None],
#     "n7HRings": ["Number of hetero 7-membered rings", Calculator(RingCount.RingCount(7,False,False,None,True)), None],
#     "n8HRings": ["Number of hetero 8-membered rings", Calculator(RingCount.RingCount(8,False,False,None,True)), None],
#     "n9HRings": ["Number of hetero 9-membered rings", Calculator(RingCount.RingCount(9,False,False,None,True)), None],
#     "n10HRings": ["Number of hetero 10-membered rings", Calculator(RingCount.RingCount(10,False,False,None,True)), None],
#     "n11HRings": ["Number of hetero 11-membered rings", Calculator(RingCount.RingCount(11,False,False,None,True)), None],
#     "n12HRings": ["Number of hetero 12-membered rings", Calculator(RingCount.RingCount(12,False,False,None,True)), None],
#     "nG3HRings": ["Number of heetero rings with 3 or more atoms", Calculator(RingCount.RingCount(3,True,False,None,True)), None],
#     "nG4HRings": ["Number of heetero rings with 4 or more atoms", Calculator(RingCount.RingCount(4,True,False,None,True)), None],
#     "nG5HRings": ["Number of heetero rings with 5 or more atoms", Calculator(RingCount.RingCount(5,True,False,None,True)), None],
#     "nG6HRings": ["Number of heetero rings with 6 or more atoms", Calculator(RingCount.RingCount(6,True,False,None,True)), None],
#     "nG7HRings": ["Number of heetero rings with 7 or more atoms", Calculator(RingCount.RingCount(7,True,False,None,True)), None],
#     "nG8HRings": ["Number of heetero rings with 8 or more atoms", Calculator(RingCount.RingCount(8,True,False,None,True)), None],
#     "nG9HRings": ["Number of heetero rings with 9 or more atoms", Calculator(RingCount.RingCount(9,True,False,None,True)), None],
#     "nG10HRings": ["Number of heetero rings with 10 or more atoms", Calculator(RingCount.RingCount(10,True,False,None,True)), None],
#     "nG11HRings": ["Number of heetero rings with 11 or more atoms", Calculator(RingCount.RingCount(11,True,False,None,True)), None],
#     "nG12HRings": ["Number of heetero rings with 12 or more atoms", Calculator(RingCount.RingCount(12,True,False,None,True)), None],
#     "nArRings": ["Number of aromatic rings", Lipinski.NumAromaticRings, Calculator(RingCount.RingCount(None,False,False,True,None))],
#     "n3ArRings": ["Number of aromatic 3-membered rings", Calculator(RingCount.RingCount(3,False,False,True,None)), None],
#     "n4ArRings": ["Number of aromatic 4-membered rings", Calculator(RingCount.RingCount(4,False,False,True,None)), None],
#     "n5ArRings": ["Number of aromatic 5-membered rings", Calculator(RingCount.RingCount(5,False,False,True,None)), None],
#     "n6ArRings": ["Number of aromatic 6-membered rings", Calculator(RingCount.RingCount(6,False,False,True,None)), None],
#     "n7ArRings": ["Number of aromatic 7-membered rings", Calculator(RingCount.RingCount(7,False,False,True,None)), None],
#     "n8ArRings": ["Number of aromatic 8-membered rings", Calculator(RingCount.RingCount(8,False,False,True,None)), None],
#     "n9ArRings": ["Number of aromatic 9-membered rings", Calculator(RingCount.RingCount(9,False,False,True,None)), None],
#     "n10ArRings": ["Number of aromatic 10-membered rings", Calculator(RingCount.RingCount(10,False,False,True,None)), None],
#     "n11ArRings": ["Number of aromatic 11-membered rings", Calculator(RingCount.RingCount(11,False,False,True,None)), None],
#     "n12ArRings": ["Number of aromatic 12-membered rings", Calculator(RingCount.RingCount(12,False,False,True,None)), None],
#     "nG3ArRings": ["Number of aromatic rings with 3 or more atoms", Calculator(RingCount.RingCount(3,True,False,True,None)), None],
#     "nG4ArRings": ["Number of aromatic rings with 4 or more atoms", Calculator(RingCount.RingCount(4,True,False,True,None)), None],
#     "nG5ArRings": ["Number of aromatic rings with 5 or more atoms", Calculator(RingCount.RingCount(5,True,False,True,None)), None],
#     "nG6ArRings": ["Number of aromatic rings with 6 or more atoms", Calculator(RingCount.RingCount(6,True,False,True,None)), None],
#     "nG7ArRings": ["Number of aromatic rings with 7 or more atoms", Calculator(RingCount.RingCount(7,True,False,True,None)), None],
#     "nG8ArRings": ["Number of aromatic rings with 8 or more atoms", Calculator(RingCount.RingCount(8,True,False,True,None)), None],
#     "nG9ArRings": ["Number of aromatic rings with 9 or more atoms", Calculator(RingCount.RingCount(9,True,False,True,None)), None],
#     "nG10ArRings": ["Number of aromatic rings with 10 or more atoms", Calculator(RingCount.RingCount(10,True,False,True,None)), None],
#     "nG11ArRings": ["Number of aromatic rings with 11 or more atoms", Calculator(RingCount.RingCount(11,True,False,True,None)), None],
#     "nG12ArRings": ["Number of aromatic rings with 12 or more atoms", Calculator(RingCount.RingCount(12,True,False,True,None)), None],
#     #TODO: add more ring descriptors

#     "BalabanJ": ["Balaban's J index", GraphDescriptors.BalabanJ, Calculator(BalabanJ.BalabanJ)],
#     "BertzCT": ["Bertz CT", GraphDescriptors.BertzCT, Calculator(BertzCT.BertzCT)],
    
    
#     #TODO: BCUT descriptors
#     #TODO: IPC descriptors
#     #TODO: AUtocorrelation descriptors
#     #TODO: Chi descriptors

#     "ETA_alpha": ["ETA core count", EtaCoreCount(False,False)],
#     "ETA_alpha_avg": ["ETA core count averaged by number of heavy atoms", EtaCoreCount(True,False)],
#     "ETA_shape_p": ["ETA shape index type p", EtaShapeIndex('p')],
#     "ETA_shape_y": ["ETA shape index type y", EtaShapeIndex('y')],
#     "ETA_shape_x": ["ETA shape index type x", EtaShapeIndex('x')],
#     "ETA_beta": ["ETA VEM count", EtaVEMCount('',False)],
#     "ETA_beta_avg": ["ETA VEM count averaged by number of heavy atoms", EtaVEMCount('',True)],
#     "ETA_beta_s": ["ETA VEM count type s", EtaVEMCount('s',False)],
#     "ETA_beta_s_avg": ["ETA VEM count type s averaged by number of heavy atoms", EtaVEMCount('s',True)],
#     "ETA_beta_ns": ["ETA VEM count type ns", EtaVEMCount('ns',False)],
#     "ETA_beta_ns_avg": ["ETA VEM count type ns averaged by number of heavy atoms", EtaVEMCount('ns',True)],
#     "ETA_beta_ns_d": ["ETA VEM count type ns_d", EtaVEMCount('ns_d',False)],
#     "ETA_beta_ns_d_avg": ["ETA VEM count type ns_d averaged by number of heavy atoms", EtaVEMCount('ns_d',True)],
#     "ETA_eta": ["ETA composite index", EtaCompositeIndex(False,False,False)],
#     "ETA_eta_avg": ["ETA composite index averaged by number of heavy atoms", EtaCompositeIndex(False,False,True)],
#     "ETA_eta_L": ["ETA composite index use local eta", EtaCompositeIndex(False,True,False)],
#     "ETA_eta_L_avg": ["ETA composite index use local eta averaged by number of heavy atoms", EtaCompositeIndex(False,True,True)],
#     "ETA_eta_R": ["ETA composite index use reference alkane", EtaCompositeIndex(True,False,False)],
#     "ETA_eta_R_avg": ["ETA composite index use reference alkane averaged by number of heavy atoms", EtaCompositeIndex(True,False,True)],
#     "ETA_eta_RL": ["ETA composite index use reference alkane and local eta", EtaCompositeIndex(True,True,False)],
#     "ETA_eta_RL_avg": ["ETA composite index use reference alkane and local eta averaged by number of heavy atoms", EtaCompositeIndex(True,True,True)],
#     "ETA_eta_F": ["ETA functionality index", EtaFunctionalityIndex(False,False)],
#     "ETA_eta_F_avg": ["ETA functionality index averaged by number of heavy atoms", EtaFunctionalityIndex(False,True)],
#     "ETA_eta_FL": ["ETA functionality index use local eta", EtaFunctionalityIndex(True,False)],
#     "ETA_eta_FL_avg": ["ETA functionality index use local eta averaged by number of heavy atoms", EtaFunctionalityIndex(True,True)],
#     "ETA_eta_B": ["ETA branching index", EtaBranchingIndex(False,False)],
#     "ETA_eta_B_avg": ["ETA branching index averaged by number of heavy atoms", EtaBranchingIndex(False,True)],
#     "ETA_eta_BR": ["ETA branching index use ring count", EtaBranchingIndex(True,False)],
#     "ETA_eta_BR_avg": ["ETA branching index use ring count averaged by number of heavy atoms", EtaBranchingIndex(True,True)],
#     "ETA_dAlpha_A": ["ETA delta alpha type A", EtaDeltaAlpha('A')],
#     "ETA_dAlpha_B": ["ETA delta alpha type B", EtaDeltaAlpha('B')],
#     "ETA_epsilon1": ["ETA epsilon all atoms", EtaEpsilon(1)],
#     "ETA_epsilon2": ["ETA epsilon heavy atoms", EtaEpsilon(2)],
#     "ETA_epsilon3": ["ETA epsilon all atoms of reference alkane", EtaEpsilon(3)],
#     "ETA_epsilon4": ["ETA epsilon all atoms of saturated carbon skeleton", EtaEpsilon(4)],
#     "ETA_epsilon5": ["ETA epsilon hydrogens bond to hetero atoms", EtaEpsilon(5)],
#     "ETA_dEpsilon_A": ["ETA delta epsilon type A", EtaDeltaEpsilon('A')],
#     "ETA_dEpsilon_B": ["ETA delta epsilon type B", EtaDeltaEpsilon('B')],
#     "ETA_dEpsilon_C": ["ETA delta epsilon type C", EtaDeltaEpsilon('C')],
#     "ETA_dEpsilon_D": ["ETA delta epsilon type D", EtaDeltaEpsilon('D')],
#     "ETA_dBeta": ["ETA delta beta", EtaDeltaBeta(False)],
#     "ETA_dBeta_avg": ["ETA delta beta averaged by number of heavy atoms", EtaDeltaBeta(True)],
#     "ETA_Psi": ["ETA psi", EtaPsi()],
#     "ETA_dPsi_A": ["ETA delta psi type A", EtaDeltaPsi('A')],
#     "ETA_dPsi_B": ["ETA delta psi type B", EtaDeltaPsi('B')],

# }

desc_shape = {
    "LabuteASA": ["Labute's approximate surface area", LabuteASA()],
    "PEOE_VSA1": ["MOE charge VSA 1", PEOE_VSA(1)],
    "PEOE_VSA2": ["MOE charge VSA 2", PEOE_VSA(2)],
    "PEOE_VSA3": ["MOE charge VSA 3", PEOE_VSA(3)],
    "PEOE_VSA4": ["MOE charge VSA 4", PEOE_VSA(4)],
    "PEOE_VSA5": ["MOE charge VSA 5", PEOE_VSA(5)],
    "PEOE_VSA6": ["MOE charge VSA 6", PEOE_VSA(6)],
    "PEOE_VSA7": ["MOE charge VSA 7", PEOE_VSA(7)],
    "PEOE_VSA8": ["MOE charge VSA 8", PEOE_VSA(8)],
    "PEOE_VSA9": ["MOE charge VSA 9", PEOE_VSA(9)],
    "PEOE_VSA10": ["MOE charge VSA 10", PEOE_VSA(10)],
    "PEOE_VSA11": ["MOE charge VSA 11", PEOE_VSA(11)],
    "PEOE_VSA12": ["MOE charge VSA 12", PEOE_VSA(12)],
    "PEOE_VSA13": ["MOE charge VSA 13", PEOE_VSA(13)],
    "PEOE_VSA14": ["MOE charge VSA 14", PEOE_VSA(14)],
    "SMR_VSA1": ["MOE MR VSA 1", SMR_VSA(1)],
    "SMR_VSA2": ["MOE MR VSA 2", SMR_VSA(2)],
    "SMR_VSA3": ["MOE MR VSA 3", SMR_VSA(3)],
    "SMR_VSA4": ["MOE MR VSA 4", SMR_VSA(4)],
    "SMR_VSA5": ["MOE MR VSA 5", SMR_VSA(5)],
    "SMR_VSA6": ["MOE MR VSA 6", SMR_VSA(6)],
    "SMR_VSA7": ["MOE MR VSA 7", SMR_VSA(7)],
    "SMR_VSA8": ["MOE MR VSA 8", SMR_VSA(8)],
    "SMR_VSA9": ["MOE MR VSA 9", SMR_VSA(9)],
    "SMR_VSA10": ["MOE MR VSA 10", SMR_VSA(10)],
    "SlogP_VSA1": ["MOE logP VSA 1", SlogP_VSA(1)],
    "SlogP_VSA2": ["MOE logP VSA 2", SlogP_VSA(2)],
    "SlogP_VSA3": ["MOE logP VSA 3", SlogP_VSA(3)],
    "SlogP_VSA4": ["MOE logP VSA 4", SlogP_VSA(4)],
    "SlogP_VSA5": ["MOE logP VSA 5", SlogP_VSA(5)],
    "SlogP_VSA6": ["MOE logP VSA 6", SlogP_VSA(6)],
    "SlogP_VSA7": ["MOE logP VSA 7", SlogP_VSA(7)],
    "SlogP_VSA8": ["MOE logP VSA 8", SlogP_VSA(8)],
    "SlogP_VSA9": ["MOE logP VSA 9", SlogP_VSA(9)],
    "SlogP_VSA10": ["MOE logP VSA 10", SlogP_VSA(10)],
    "SlogP_VSA11": ["MOE logP VSA 11", SlogP_VSA(11)],
    "SlogP_VSA12": ["MOE logP VSA 12", SlogP_VSA(12)],
    "EState_VSA1": ["MOE EState VSA 1", EState_VSA(1)],
    "EState_VSA2": ["MOE EState VSA 2", EState_VSA(2)],
    "EState_VSA3": ["MOE EState VSA 3", EState_VSA(3)],
    "EState_VSA4": ["MOE EState VSA 4", EState_VSA(4)],
    "EState_VSA5": ["MOE EState VSA 5", EState_VSA(5)],
    "EState_VSA6": ["MOE EState VSA 6", EState_VSA(6)],
    "EState_VSA7": ["MOE EState VSA 7", EState_VSA(7)],
    "EState_VSA8": ["MOE EState VSA 8", EState_VSA(8)],
    "EState_VSA9": ["MOE EState VSA 9", EState_VSA(9)],
    "EState_VSA10": ["MOE EState VSA 10", EState_VSA(10)],
    "EState_VSA11": ["MOE EState VSA 11", EState_VSA(11)],
    "VSA_EState1": ["MOE VSA EState 1", VSA_EState(1)],
    "VSA_EState2": ["MOE VSA EState 2", VSA_EState(2)],
    "VSA_EState3": ["MOE VSA EState 3", VSA_EState(3)],
    "VSA_EState4": ["MOE VSA EState 4", VSA_EState(4)],
    "VSA_EState5": ["MOE VSA EState 5", VSA_EState(5)],
    "VSA_EState6": ["MOE VSA EState 6", VSA_EState(6)],
    "VSA_EState7": ["MOE VSA EState 7", VSA_EState(7)],
    "VSA_EState8": ["MOE VSA EState 8", VSA_EState(8)],
    "VSA_EState9": ["MOE VSA EState 9", VSA_EState(9)],
    "VSA_EState10": ["MOE VSA EState 10", VSA_EState(10)],

    "McGowan": ["McGowan volume", McGowan()],
    "Radius": ["Radius of gyration", Radius()],
    "Diameter": ["Diameter of gyration", Diameter()],
    "TopoShapeIndex": ["Topological shape index", TopologicalShapeIndex()],
    "PetitjeanIndex": ["Petitjean index", PetitjeanIndex()],
    "VABC": ["Van der Waals volume (ABC)", VABC()],
    "Asphericity": ["Molecular asphericity", Asphericity()],
    "Eccentricity": ["Molecular eccentricity", Eccentricity()],
    "InertialShapeFactor": ["Inertial shape factor", InertialShapeFactor()],
    "NPR1": ["Normalized principal moments ratio 1 (=I1/I3)", NPR(1)],
    "NPR2": ["Normalized principal moments ratio 2 (=I2/I3)", NPR(2)],
    "PBF": ["Plane of best fit", PBF()],
    "PMI1": ["First (smallest) principal moment of inertia", PMI(1)],
    "PMI2": ["Second principal moment of inertia", PMI(2)],
    "PMI3": ["Third principal moment of inertia", PMI(3)],
    "SpherocityIndex": ["Molecular spherocity index", SpherocityIndex()],
    "Kappa1": ["Kappa shape index 1", Kappa(1)],
    "Kappa2": ["Kappa shape index 2", Kappa(2)],
    "Kappa3": ["Kappa shape index 3", Kappa(3)],
    "TPSA": ["Topological polar surface area", TPSA()],

    "HybRatio": ["Hybridization ratio", HybRatio()],
    "C1SP1": ["Number of sp Carbons bonded to 1 Carbon", Carbon(1,1)],
    "C2SP1": ["Number of sp Carbons bonded to 2 Carbons", Carbon(2,1)],
    "C1SP2": ["Number of sp2 Carbons bonded to 1 Carbon", Carbon(1,2)],
    "C2SP2": ["Number of sp2 Carbons bonded to 2 Carbons", Carbon(2,2)],
    "C3SP2": ["Number of sp2 Carbons bonded to 3 Carbons", Carbon(3,2)],
    "C1SP3": ["Number of sp3 Carbons bonded to 1 Carbon", Carbon(1,3)],
    "C2SP3": ["Number of sp3 Carbons bonded to 2 Carbons", Carbon(2,3)],
    "C3SP3": ["Number of sp3 Carbons bonded to 3 Carbons", Carbon(3,3)],
    "C4SP3": ["Number of sp3 Carbons bonded to 4 Carbons", Carbon(4,3)],
}

desc_electronic = {
    "EEM": ["EEM atomic partial charges", Charge("EEM")],
    "MaxAbsPartialCharge": ["Maximum absolute partial charge", Charge('MaxAbsPartialCharge')],
    "MaxPartialCharge": ["Maximum partial charge", Charge('MaxPartialCharge')],
    "MinAbsPartialCharge": ["Minimum absolute partial charge", Charge('MinAbsPartialCharge')],
    "MinPartialCharge": ["Minimum partial charge", Charge('MinPartialCharge')],
    "APol": ["Atomic polarizability", Polarizability('atom')],
    "BPol": ["Bond polarizability", Polarizability('bond')],

    "NsLi": ["Number of atom-type E-State -Li", AtomTypeEState('count', 'sLi')],
    "NssBe": ["Number of atom-type E-State -Be-", AtomTypeEState('count', 'ssBe')],
    "NssssBe": ["Number of atom-type E-State >Be<", AtomTypeEState('count', 'ssssBe')],
    "NssBH": ["Number of atom-type E-State -BH-", AtomTypeEState('count', 'ssBH')],
    "NsssB": ["Number of atom-type E-State >B-", AtomTypeEState('count', 'sssB')],
    "NssssB": ["Number of atom-type E-State >B<", AtomTypeEState('count', 'ssssB')],
    "NsCH3": ["Number of atom-type E-State -CH3", AtomTypeEState('count', 'sCH3')],
    "NdCH2": ["Number of atom-type E-State =CH2", AtomTypeEState('count', 'dCH2')],
    "NssCH2": ["Number of atom-type E-State -CH2-", AtomTypeEState('count', 'ssCH2')],
    "NtCH": ["Number of atom-type E-State #CH", AtomTypeEState('count', 'tCH')],
    "NdsCH": ["Number of atom-type E-State =CH-", AtomTypeEState('count', 'dsCH')],
    "NaaCH": ["Number of atom-type E-State :CH:", AtomTypeEState('count', 'aaCH')],
    "NsssCH": ["Number of atom-type E-State >CH-", AtomTypeEState('count', 'sssCH')],
    "NddC": ["Number of atom-type E-State =C=", AtomTypeEState('count', 'ddC')],
    "NtsC": ["Number of atom-type E-State #C-", AtomTypeEState('count', 'tsC')],
    "NdssC": ["Number of atom-type E-State =C<", AtomTypeEState('count', 'dssC')],
    "NaasC": ["Number of atom-type E-State :C:-", AtomTypeEState('count', 'aasC')],
    "NaaaC": ["Number of atom-type E-State ::C:", AtomTypeEState('count', 'aaaC')],
    "NssssC": ["Number of atom-type E-State >C<", AtomTypeEState('count', 'ssssC')],
    "NsNH3": ["Number of atom-type E-State -NH3", AtomTypeEState('count', 'sNH3')],
    "NsNH2": ["Number of atom-type E-State -NH2", AtomTypeEState('count', 'sNH2')],
    "NssNH2": ["Number of atom-type E-State -NH2-", AtomTypeEState('count', 'ssNH2')],
    "NdNH": ["Number of atom-type E-State =NH", AtomTypeEState('count', 'dNH')],
    "NssNH": ["Number of atom-type E-State -NH-", AtomTypeEState('count', 'ssNH')],
    "NaaNH": ["Number of atom-type E-State :NH:", AtomTypeEState('count', 'aaNH')],
    "NtN": ["Number of atom-type E-State #N", AtomTypeEState('count', 'tN')],
    "NsssNH": ["Number of atom-type E-State >NH-", AtomTypeEState('count', 'sssNH')],
    "NdsN": ["Number of atom-type E-State =N-", AtomTypeEState('count', 'dsN')],
    "NaaN": ["Number of atom-type E-State :N:", AtomTypeEState('count', 'aaN')],
    "NsssN": ["Number of atom-type E-State >N-", AtomTypeEState('count', 'sssN')],
    "NddsN": ["Number of atom-type E-State =N=-", AtomTypeEState('count', 'dsN')],
    "NaasN": ["Number of atom-type E-State :N:-", AtomTypeEState('count', 'aasN')],
    "NssssN": ["Number of atom-type E-State >N<", AtomTypeEState('count', 'ssssN')],
    "NsOH": ["Number of atom-type E-State -OH", AtomTypeEState('count', 'sOH')],
    "NdO": ["Number of atom-type E-State =O", AtomTypeEState('count', 'dO')],
    "NssO": ["Number of atom-type E-State -O-", AtomTypeEState('count', 'ssO')],
    "NaaO": ["Number of atom-type E-State :O:", AtomTypeEState('count', 'aaO')],
    "NsF": ["Number of atom-type E-State -F", AtomTypeEState('count', 'sF')],
    "NsSiH3": ["Number of atom-type E-State -SiH3", AtomTypeEState('count', 'sSiH3')],
    "NssSiH2": ["Number of atom-type E-State -SiH2-", AtomTypeEState('count', 'ssSiH2')],
    "NsssSiH": ["Number of atom-type E-State >SiH-", AtomTypeEState('count', 'sssSiH')],
    "NssssSi": ["Number of atom-type E-State >Si<", AtomTypeEState('count', 'ssssSi')],
    "NsPH2": ["Number of atom-type E-State -PH2", AtomTypeEState('count', 'sPH2')],
    "NssPH": ["Number of atom-type E-State -PH-", AtomTypeEState('count', 'ssPH')],
    "NsssP": ["Number of atom-type E-State >P-", AtomTypeEState('count', 'sssP')],
    "NdsssP": ["Number of atom-type E-State =-P<", AtomTypeEState('count', 'dsssP')],
    "NsssssP": ["Number of atom-type E-State #P<", AtomTypeEState('count', 'sssssP')],
    "NsSH": ["Number of atom-type E-State -SH", AtomTypeEState('count', 'sSH')],
    "NdS": ["Number of atom-type E-State =S", AtomTypeEState('count', 'dS')],
    "NssS": ["Number of atom-type E-State -S-", AtomTypeEState('count', 'ssS')],
    "NaaS": ["Number of atom-type E-State :S:", AtomTypeEState('count', 'aaS')],
    "NdssS": ["Number of atom-type E-State =S<", AtomTypeEState('count', 'dssS')],
    "NddssS": ["Number of atom-type E-State =-S-=", AtomTypeEState('count', 'ddssS')],
    "NsCl": ["Number of atom-type E-State -Cl", AtomTypeEState('count', 'sCl')],
    "NsGeH3": ["Number of atom-type E-State -GeH3", AtomTypeEState('count', 'sGeH3')],
    "NssGeH2": ["Number of atom-type E-State -GeH2-", AtomTypeEState('count', 'ssGeH2')],
    "NsssGeH": ["Number of atom-type E-State >GeH-", AtomTypeEState('count', 'sssGeH')],
    "NssssGe": ["Number of atom-type E-State >Ge<", AtomTypeEState('count', 'ssssGe')],
    "NsAsH2": ["Number of atom-type E-State -AsH2", AtomTypeEState('count', 'sAsH2')],
    "NssAsH": ["Number of atom-type E-State -AsH-", AtomTypeEState('count', 'ssAsH')],
    "NsssAs": ["Number of atom-type E-State >As-", AtomTypeEState('count', 'sssAs')],
    "NsssdAs": ["Number of atom-type E-State >As-=", AtomTypeEState('count', 'sssdAs')],
    "NsssssAs": ["Number of atom-type E-State #As<", AtomTypeEState('count', 'sssssAs')],
    "NsSeH": ["Number of atom-type E-State -SeH", AtomTypeEState('count', 'sSeH')],
    "NdSe": ["Number of atom-type E-State =Se", AtomTypeEState('count', 'dSe')],
    "NssSe": ["Number of atom-type E-State -Se-", AtomTypeEState('count', 'ssSe')],
    "NaaSe": ["Number of atom-type E-State :Se:", AtomTypeEState('count', 'aaSe')],
    "NdssSe": ["Number of atom-type E-State =Se<", AtomTypeEState('count', 'dssSe')],
    "NddssSe": ["Number of atom-type E-State =-Se-=", AtomTypeEState('count', 'ddssSe')],
    "NsBr": ["Number of atom-type E-State -Br", AtomTypeEState('count', 'sBr')],
    "NsSnH3": ["Number of atom-type E-State -SnH3", AtomTypeEState('count', 'sSnH3')],
    "NssSnH2": ["Number of atom-type E-State -SnH2-", AtomTypeEState('count', 'ssSnH2')],
    "NsssSnH": ["Number of atom-type E-State >SnH-", AtomTypeEState('count', 'sssSnH')],
    "NssssSn": ["Number of atom-type E-State >Sn<", AtomTypeEState('count', 'ssssSn')],
    "NsI": ["Number of atom-type E-State -I", AtomTypeEState('count', 'sI')],
    "NsPbH3": ["Number of atom-type E-State -PbH3", AtomTypeEState('count', 'sPbH3')],
    "NssPbH2": ["Number of atom-type E-State -PbH2-", AtomTypeEState('count', 'ssPbH2')],
    "NsssPbH": ["Number of atom-type E-State >PbH-", AtomTypeEState('count', 'sssPbH')],
    "NssssPb": ["Number of atom-type E-State >Pb<", AtomTypeEState('count', 'ssssPb')],

    "SsLi": ["Sum of atom-type E-State -Li", AtomTypeEState('sum', 'sLi')],
    "SssBe": ["Sum of atom-type E-State -Be-", AtomTypeEState('sum', 'ssBe')],
    "SssssBe": ["Sum of atom-type E-State >Be<", AtomTypeEState('sum', 'ssssBe')],
    "SssBH": ["Sum of atom-type E-State -BH-", AtomTypeEState('sum', 'ssBH')],
    "SsssB": ["Sum of atom-type E-State >B-", AtomTypeEState('sum', 'sssB')],
    "SssssB": ["Sum of atom-type E-State >B<", AtomTypeEState('sum', 'ssssB')],
    "SsCH3": ["Sum of atom-type E-State -CH3", AtomTypeEState('sum', 'sCH3')],
    "SdCH2": ["Sum of atom-type E-State =CH2", AtomTypeEState('sum', 'dCH2')],
    "SssCH2": ["Sum of atom-type E-State -CH2-", AtomTypeEState('sum', 'ssCH2')],
    "StCH": ["Sum of atom-type E-State #CH", AtomTypeEState('sum', 'tCH')],
    "SdsCH": ["Sum of atom-type E-State =CH-", AtomTypeEState('sum', 'dsCH')],
    "SaaCH": ["Sum of atom-type E-State :CH:", AtomTypeEState('sum', 'aaCH')],
    "SsssCH": ["Sum of atom-type E-State >CH-", AtomTypeEState('sum', 'sssCH')],
    "SddC": ["Sum of atom-type E-State =C=", AtomTypeEState('sum', 'ddC')],
    "StsC": ["Sum of atom-type E-State #C-", AtomTypeEState('sum', 'tsC')],
    "SdssC": ["Sum of atom-type E-State =C<", AtomTypeEState('sum', 'dssC')],
    "SaasC": ["Sum of atom-type E-State :C:-", AtomTypeEState('sum', 'aasC')],
    "SaaaC": ["Sum of atom-type E-State ::C:", AtomTypeEState('sum', 'aaaC')],
    "SssssC": ["Sum of atom-type E-State >C<", AtomTypeEState('sum', 'ssssC')],
    "SsNH3": ["Sum of atom-type E-State -NH3", AtomTypeEState('sum', 'sNH3')],
    "SsNH2": ["Sum of atom-type E-State -NH2", AtomTypeEState('sum', 'sNH2')],
    "SssNH2": ["Sum of atom-type E-State -NH2-", AtomTypeEState('sum', 'ssNH2')],
    "SdNH": ["Sum of atom-type E-State =NH", AtomTypeEState('sum', 'dNH')],
    "SssNH": ["Sum of atom-type E-State -NH-", AtomTypeEState('sum', 'ssNH')],
    "SaaNH": ["Sum of atom-type E-State :NH:", AtomTypeEState('sum', 'aaNH')],
    "StN": ["Sum of atom-type E-State #N", AtomTypeEState('sum', 'tN')],
    "SsssNH": ["Sum of atom-type E-State >NH-", AtomTypeEState('sum', 'sssNH')],
    "SdsN": ["Sum of atom-type E-State =N-", AtomTypeEState('sum', 'dsN')],
    "SaaN": ["Sum of atom-type E-State :N:", AtomTypeEState('sum', 'aaN')],
    "SsssN": ["Sum of atom-type E-State >N-", AtomTypeEState('sum', 'sssN')],
    "SddsN": ["Sum of atom-type E-State =N=-", AtomTypeEState('sum', 'dsN')],
    "SaasN": ["Sum of atom-type E-State :N:-", AtomTypeEState('sum', 'aasN')],
    "SssssN": ["Sum of atom-type E-State >N<", AtomTypeEState('sum', 'ssssN')],
    "SsOH": ["Sum of atom-type E-State -OH", AtomTypeEState('sum', 'sOH')],
    "SdO": ["Sum of atom-type E-State =O", AtomTypeEState('sum', 'dO')],
    "SssO": ["Sum of atom-type E-State -O-", AtomTypeEState('sum', 'ssO')],
    "SaaO": ["Sum of atom-type E-State :O:", AtomTypeEState('sum', 'aaO')],
    "SsF": ["Sum of atom-type E-State -F", AtomTypeEState('sum', 'sF')],
    "SsSiH3": ["Sum of atom-type E-State -SiH3", AtomTypeEState('sum', 'sSiH3')],
    "SssSiH2": ["Sum of atom-type E-State -SiH2-", AtomTypeEState('sum', 'ssSiH2')],
    "SsssSiH": ["Sum of atom-type E-State >SiH-", AtomTypeEState('sum', 'sssSiH')],
    "SssssSi": ["Sum of atom-type E-State >Si<", AtomTypeEState('sum', 'ssssSi')],
    "SsPH2": ["Sum of atom-type E-State -PH2", AtomTypeEState('sum', 'sPH2')],
    "SssPH": ["Sum of atom-type E-State -PH-", AtomTypeEState('sum', 'ssPH')],
    "SsssP": ["Sum of atom-type E-State >P-", AtomTypeEState('sum', 'sssP')],
    "SdsssP": ["Sum of atom-type E-State =-P<", AtomTypeEState('sum', 'dsssP')],
    "SsssssP": ["Sum of atom-type E-State #P<", AtomTypeEState('sum', 'sssssP')],
    "SsSH": ["Sum of atom-type E-State -SH", AtomTypeEState('sum', 'sSH')],
    "SdS": ["Sum of atom-type E-State =S", AtomTypeEState('sum', 'dS')],
    "SssS": ["Sum of atom-type E-State -S-", AtomTypeEState('sum', 'ssS')],
    "SaaS": ["Sum of atom-type E-State :S:", AtomTypeEState('sum', 'aaS')],
    "SdssS": ["Sum of atom-type E-State =S<", AtomTypeEState('sum', 'dssS')],
    "SddssS": ["Sum of atom-type E-State =-S-=", AtomTypeEState('sum', 'ddssS')],
    "SsCl": ["Sum of atom-type E-State -Cl", AtomTypeEState('sum', 'sCl')],
    "SsGeH3": ["Sum of atom-type E-State -GeH3", AtomTypeEState('sum', 'sGeH3')],
    "SssGeH2": ["Sum of atom-type E-State -GeH2-", AtomTypeEState('sum', 'ssGeH2')],
    "SsssGeH": ["Sum of atom-type E-State >GeH-", AtomTypeEState('sum', 'sssGeH')],
    "SssssGe": ["Sum of atom-type E-State >Ge<", AtomTypeEState('sum', 'ssssGe')],
    "SsAsH2": ["Sum of atom-type E-State -AsH2", AtomTypeEState('sum', 'sAsH2')],
    "SssAsH": ["Sum of atom-type E-State -AsH-", AtomTypeEState('sum', 'ssAsH')],
    "SsssAs": ["Sum of atom-type E-State >As-", AtomTypeEState('sum', 'sssAs')],
    "SsssdAs": ["Sum of atom-type E-State >As-=", AtomTypeEState('sum', 'sssdAs')],
    "SsssssAs": ["Sum of atom-type E-State #As<", AtomTypeEState('sum', 'sssssAs')],
    "SsSeH": ["Sum of atom-type E-State -SeH", AtomTypeEState('sum', 'sSeH')],
    "SdSe": ["Sum of atom-type E-State =Se", AtomTypeEState('sum', 'dSe')],
    "SssSe": ["Sum of atom-type E-State -Se-", AtomTypeEState('sum', 'ssSe')],
    "SaaSe": ["Sum of atom-type E-State :Se:", AtomTypeEState('sum', 'aaSe')],
    "SdssSe": ["Sum of atom-type E-State =Se<", AtomTypeEState('sum', 'dssSe')],
    "SddssSe": ["Sum of atom-type E-State =-Se-=", AtomTypeEState('sum', 'ddssSe')],
    "SsBr": ["Sum of atom-type E-State -Br", AtomTypeEState('sum', 'sBr')],
    "SsSnH3": ["Sum of atom-type E-State -SnH3", AtomTypeEState('sum', 'sSnH3')],
    "SssSnH2": ["Sum of atom-type E-State -SnH2-", AtomTypeEState('sum', 'ssSnH2')],
    "SsssSnH": ["Sum of atom-type E-State >SnH-", AtomTypeEState('sum', 'sssSnH')],
    "SssssSn": ["Sum of atom-type E-State >Sn<", AtomTypeEState('sum', 'ssssSn')],
    "SsI": ["Sum of atom-type E-State -I", AtomTypeEState('sum', 'sI')],
    "SsPbH3": ["Sum of atom-type E-State -PbH3", AtomTypeEState('sum', 'sPbH3')],
    "SssPbH2": ["Sum of atom-type E-State -PbH2-", AtomTypeEState('sum', 'ssPbH2')],
    "SsssPbH": ["Sum of atom-type E-State >PbH-", AtomTypeEState('sum', 'sssPbH')],
    "SssssPb": ["Sum of atom-type E-State >Pb<", AtomTypeEState('sum', 'ssssPb')],

    "MAXsLi": ["Maximum of atom-type E-State -Li", AtomTypeEState('max', 'sLi')],
    "MAXssBe": ["Maximum of atom-type E-State -Be-", AtomTypeEState('max', 'ssBe')],
    "MAXssssBe": ["Maximum of atom-type E-State >Be<", AtomTypeEState('max', 'ssssBe')],
    "MAXssBH": ["Maximum of atom-type E-State -BH-", AtomTypeEState('max', 'ssBH')],
    "MAXsssB": ["Maximum of atom-type E-State >B-", AtomTypeEState('max', 'sssB')],
    "MAXssssB": ["Maximum of atom-type E-State >B<", AtomTypeEState('max', 'ssssB')],
    "MAXsCH3": ["Maximum of atom-type E-State -CH3", AtomTypeEState('max', 'sCH3')],
    "MAXdCH2": ["Maximum of atom-type E-State =CH2", AtomTypeEState('max', 'dCH2')],
    "MAXssCH2": ["Maximum of atom-type E-State -CH2-", AtomTypeEState('max', 'ssCH2')],
    "MAXtCH": ["Maximum of atom-type E-State #CH", AtomTypeEState('max', 'tCH')],
    "MAXdsCH": ["Maximum of atom-type E-State =CH-", AtomTypeEState('max', 'dsCH')],
    "MAXaaCH": ["Maximum of atom-type E-State :CH:", AtomTypeEState('max', 'aaCH')],
    "MAXsssCH": ["Maximum of atom-type E-State >CH-", AtomTypeEState('max', 'sssCH')],
    "MAXddC": ["Maximum of atom-type E-State =C=", AtomTypeEState('max', 'ddC')],
    "MAXtsC": ["Maximum of atom-type E-State #C-", AtomTypeEState('max', 'tsC')],
    "MAXdssC": ["Maximum of atom-type E-State =C<", AtomTypeEState('max', 'dssC')],
    "MAXaasC": ["Maximum of atom-type E-State :C:-", AtomTypeEState('max', 'aasC')],
    "MAXaaaC": ["Maximum of atom-type E-State ::C:", AtomTypeEState('max', 'aaaC')],
    "MAXssssC": ["Maximum of atom-type E-State >C<", AtomTypeEState('max', 'ssssC')],
    "MAXsNH3": ["Maximum of atom-type E-State -NH3", AtomTypeEState('max', 'sNH3')],
    "MAXsNH2": ["Maximum of atom-type E-State -NH2", AtomTypeEState('max', 'sNH2')],
    "MAXssNH2": ["Maximum of atom-type E-State -NH2-", AtomTypeEState('max', 'ssNH2')],
    "MAXdNH": ["Maximum of atom-type E-State =NH", AtomTypeEState('max', 'dNH')],
    "MAXssNH": ["Maximum of atom-type E-State -NH-", AtomTypeEState('max', 'ssNH')],
    "MAXaaNH": ["Maximum of atom-type E-State :NH:", AtomTypeEState('max', 'aaNH')],
    "MAXtN": ["Maximum of atom-type E-State #N", AtomTypeEState('max', 'tN')],
    "MAXsssNH": ["Maximum of atom-type E-State >NH-", AtomTypeEState('max', 'sssNH')],
    "MAXdsN": ["Maximum of atom-type E-State =N-", AtomTypeEState('max', 'dsN')],
    "MAXaaN": ["Maximum of atom-type E-State :N:", AtomTypeEState('max', 'aaN')],
    "MAXsssN": ["Maximum of atom-type E-State >N-", AtomTypeEState('max', 'sssN')],
    "MAXddsN": ["Maximum of atom-type E-State =N=-", AtomTypeEState('max', 'dsN')],
    "MAXaasN": ["Maximum of atom-type E-State :N:-", AtomTypeEState('max', 'aasN')],
    "MAXssssN": ["Maximum of atom-type E-State >N<", AtomTypeEState('max', 'ssssN')],
    "MAXsOH": ["Maximum of atom-type E-State -OH", AtomTypeEState('max', 'sOH')],
    "MAXdO": ["Maximum of atom-type E-State =O", AtomTypeEState('max', 'dO')],
    "MAXssO": ["Maximum of atom-type E-State -O-", AtomTypeEState('max', 'ssO')],
    "MAXaaO": ["Maximum of atom-type E-State :O:", AtomTypeEState('max', 'aaO')],
    "MAXsF": ["Maximum of atom-type E-State -F", AtomTypeEState('max', 'sF')],
    "MAXsSiH3": ["Maximum of atom-type E-State -SiH3", AtomTypeEState('max', 'sSiH3')],
    "MAXssSiH2": ["Maximum of atom-type E-State -SiH2-", AtomTypeEState('max', 'ssSiH2')],
    "MAXsssSiH": ["Maximum of atom-type E-State >SiH-", AtomTypeEState('max', 'sssSiH')],
    "MAXssssSi": ["Maximum of atom-type E-State >Si<", AtomTypeEState('max', 'ssssSi')],
    "MAXsPH2": ["Maximum of atom-type E-State -PH2", AtomTypeEState('max', 'sPH2')],
    "MAXssPH": ["Maximum of atom-type E-State -PH-", AtomTypeEState('max', 'ssPH')],
    "MAXsssP": ["Maximum of atom-type E-State >P-", AtomTypeEState('max', 'sssP')],
    "MAXdsssP": ["Maximum of atom-type E-State =-P<", AtomTypeEState('max', 'dsssP')],
    "MAXsssssP": ["Maximum of atom-type E-State #P<", AtomTypeEState('max', 'sssssP')],
    "MAXsSH": ["Maximum of atom-type E-State -SH", AtomTypeEState('max', 'sSH')],
    "MAXdS": ["Maximum of atom-type E-State =S", AtomTypeEState('max', 'dS')],
    "MAXssS": ["Maximum of atom-type E-State -S-", AtomTypeEState('max', 'ssS')],
    "MAXaaS": ["Maximum of atom-type E-State :S:", AtomTypeEState('max', 'aaS')],
    "MAXdssS": ["Maximum of atom-type E-State =S<", AtomTypeEState('max', 'dssS')],
    "MAXddssS": ["Maximum of atom-type E-State =-S-=", AtomTypeEState('max', 'ddssS')],
    "MAXsCl": ["Maximum of atom-type E-State -Cl", AtomTypeEState('max', 'sCl')],
    "MAXsGeH3": ["Maximum of atom-type E-State -GeH3", AtomTypeEState('max', 'sGeH3')],
    "MAXssGeH2": ["Maximum of atom-type E-State -GeH2-", AtomTypeEState('max', 'ssGeH2')],
    "MAXsssGeH": ["Maximum of atom-type E-State >GeH-", AtomTypeEState('max', 'sssGeH')],
    "MAXssssGe": ["Maximum of atom-type E-State >Ge<", AtomTypeEState('max', 'ssssGe')],
    "MAXsAsH2": ["Maximum of atom-type E-State -AsH2", AtomTypeEState('max', 'sAsH2')],
    "MAXssAsH": ["Maximum of atom-type E-State -AsH-", AtomTypeEState('max', 'ssAsH')],
    "MAXsssAs": ["Maximum of atom-type E-State >As-", AtomTypeEState('max', 'sssAs')],
    "MAXsssdAs": ["Maximum of atom-type E-State >As-=", AtomTypeEState('max', 'sssdAs')],
    "MAXsssssAs": ["Maximum of atom-type E-State #As<", AtomTypeEState('max', 'sssssAs')],
    "MAXsSeH": ["Maximum of atom-type E-State -SeH", AtomTypeEState('max', 'sSeH')],
    "MAXdSe": ["Maximum of atom-type E-State =Se", AtomTypeEState('max', 'dSe')],
    "MAXssSe": ["Maximum of atom-type E-State -Se-", AtomTypeEState('max', 'ssSe')],
    "MAXaaSe": ["Maximum of atom-type E-State :Se:", AtomTypeEState('max', 'aaSe')],
    "MAXdssSe": ["Maximum of atom-type E-State =Se<", AtomTypeEState('max', 'dssSe')],
    "MAXddssSe": ["Maximum of atom-type E-State =-Se-=", AtomTypeEState('max', 'ddssSe')],
    "MAXsBr": ["Maximum of atom-type E-State -Br", AtomTypeEState('max', 'sBr')],
    "MAXsSnH3": ["Maximum of atom-type E-State -SnH3", AtomTypeEState('max', 'sSnH3')],
    "MAXssSnH2": ["Maximum of atom-type E-State -SnH2-", AtomTypeEState('max', 'ssSnH2')],
    "MAXsssSnH": ["Maximum of atom-type E-State >SnH-", AtomTypeEState('max', 'sssSnH')],
    "MAXssssSn": ["Maximum of atom-type E-State >Sn<", AtomTypeEState('max', 'ssssSn')],
    "MAXsI": ["Maximum of atom-type E-State -I", AtomTypeEState('max', 'sI')],
    "MAXsPbH3": ["Maximum of atom-type E-State -PbH3", AtomTypeEState('max', 'sPbH3')],
    "MAXssPbH2": ["Maximum of atom-type E-State -PbH2-", AtomTypeEState('max', 'ssPbH2')],
    "MAXsssPbH": ["Maximum of atom-type E-State >PbH-", AtomTypeEState('max', 'sssPbH')],
    "MAXssssPb": ["Maximum of atom-type E-State >Pb<", AtomTypeEState('max', 'ssssPb')],

    "MINsLi": ["Minimum of atom-type E-State -Li", AtomTypeEState('min', 'sLi')],
    "MINssBe": ["Minimum of atom-type E-State -Be-", AtomTypeEState('min', 'ssBe')],
    "MINssssBe": ["Minimum of atom-type E-State >Be<", AtomTypeEState('min', 'ssssBe')],
    "MINssBH": ["Minimum of atom-type E-State -BH-", AtomTypeEState('min', 'ssBH')],
    "MINsssB": ["Minimum of atom-type E-State >B-", AtomTypeEState('min', 'sssB')],
    "MINssssB": ["Minimum of atom-type E-State >B<", AtomTypeEState('min', 'ssssB')],
    "MINsCH3": ["Minimum of atom-type E-State -CH3", AtomTypeEState('min', 'sCH3')],
    "MINdCH2": ["Minimum of atom-type E-State =CH2", AtomTypeEState('min', 'dCH2')],
    "MINssCH2": ["Minimum of atom-type E-State -CH2-", AtomTypeEState('min', 'ssCH2')],
    "MINtCH": ["Minimum of atom-type E-State #CH", AtomTypeEState('min', 'tCH')],
    "MINdsCH": ["Minimum of atom-type E-State =CH-", AtomTypeEState('min', 'dsCH')],
    "MINaaCH": ["Minimum of atom-type E-State :CH:", AtomTypeEState('min', 'aaCH')],
    "MINsssCH": ["Minimum of atom-type E-State >CH-", AtomTypeEState('min', 'sssCH')],
    "MINddC": ["Minimum of atom-type E-State =C=", AtomTypeEState('min', 'ddC')],
    "MINtsC": ["Minimum of atom-type E-State #C-", AtomTypeEState('min', 'tsC')],
    "MINdssC": ["Minimum of atom-type E-State =C<", AtomTypeEState('min', 'dssC')],
    "MINaasC": ["Minimum of atom-type E-State :C:-", AtomTypeEState('min', 'aasC')],
    "MINaaaC": ["Minimum of atom-type E-State ::C:", AtomTypeEState('min', 'aaaC')],
    "MINssssC": ["Minimum of atom-type E-State >C<", AtomTypeEState('min', 'ssssC')],
    "MINsNH3": ["Minimum of atom-type E-State -NH3", AtomTypeEState('min', 'sNH3')],
    "MINsNH2": ["Minimum of atom-type E-State -NH2", AtomTypeEState('min', 'sNH2')],
    "MINssNH2": ["Minimum of atom-type E-State -NH2-", AtomTypeEState('min', 'ssNH2')],
    "MINdNH": ["Minimum of atom-type E-State =NH", AtomTypeEState('min', 'dNH')],
    "MINssNH": ["Minimum of atom-type E-State -NH-", AtomTypeEState('min', 'ssNH')],
    "MINaaNH": ["Minimum of atom-type E-State :NH:", AtomTypeEState('min', 'aaNH')],
    "MINtN": ["Minimum of atom-type E-State #N", AtomTypeEState('min', 'tN')],
    "MINsssNH": ["Minimum of atom-type E-State >NH-", AtomTypeEState('min', 'sssNH')],
    "MINdsN": ["Minimum of atom-type E-State =N-", AtomTypeEState('min', 'dsN')],
    "MINaaN": ["Minimum of atom-type E-State :N:", AtomTypeEState('min', 'aaN')],
    "MINsssN": ["Minimum of atom-type E-State >N-", AtomTypeEState('min', 'sssN')],
    "MINddsN": ["Minimum of atom-type E-State =N=-", AtomTypeEState('min', 'dsN')],
    "MINaasN": ["Minimum of atom-type E-State :N:-", AtomTypeEState('min', 'aasN')],
    "MINssssN": ["Minimum of atom-type E-State >N<", AtomTypeEState('min', 'ssssN')],
    "MINsOH": ["Minimum of atom-type E-State -OH", AtomTypeEState('min', 'sOH')],
    "MINdO": ["Minimum of atom-type E-State =O", AtomTypeEState('min', 'dO')],
    "MINssO": ["Minimum of atom-type E-State -O-", AtomTypeEState('min', 'ssO')],
    "MINaaO": ["Minimum of atom-type E-State :O:", AtomTypeEState('min', 'aaO')],
    "MINsF": ["Minimum of atom-type E-State -F", AtomTypeEState('min', 'sF')],
    "MINsSiH3": ["Minimum of atom-type E-State -SiH3", AtomTypeEState('min', 'sSiH3')],
    "MINssSiH2": ["Minimum of atom-type E-State -SiH2-", AtomTypeEState('min', 'ssSiH2')],
    "MINsssSiH": ["Minimum of atom-type E-State >SiH-", AtomTypeEState('min', 'sssSiH')],
    "MINssssSi": ["Minimum of atom-type E-State >Si<", AtomTypeEState('min', 'ssssSi')],
    "MINsPH2": ["Minimum of atom-type E-State -PH2", AtomTypeEState('min', 'sPH2')],
    "MINssPH": ["Minimum of atom-type E-State -PH-", AtomTypeEState('min', 'ssPH')],
    "MINsssP": ["Minimum of atom-type E-State >P-", AtomTypeEState('min', 'sssP')],
    "MINdsssP": ["Minimum of atom-type E-State =-P<", AtomTypeEState('min', 'dsssP')],
    "MINsssssP": ["Minimum of atom-type E-State #P<", AtomTypeEState('min', 'sssssP')],
    "MINsSH": ["Minimum of atom-type E-State -SH", AtomTypeEState('min', 'sSH')],
    "MINdS": ["Minimum of atom-type E-State =S", AtomTypeEState('min', 'dS')],
    "MINssS": ["Minimum of atom-type E-State -S-", AtomTypeEState('min', 'ssS')],
    "MINaaS": ["Minimum of atom-type E-State :S:", AtomTypeEState('min', 'aaS')],
    "MINdssS": ["Minimum of atom-type E-State =S<", AtomTypeEState('min', 'dssS')],
    "MINddssS": ["Minimum of atom-type E-State =-S-=", AtomTypeEState('min', 'ddssS')],
    "MINsCl": ["Minimum of atom-type E-State -Cl", AtomTypeEState('min', 'sCl')],
    "MINsGeH3": ["Minimum of atom-type E-State -GeH3", AtomTypeEState('min', 'sGeH3')],
    "MINssGeH2": ["Minimum of atom-type E-State -GeH2-", AtomTypeEState('min', 'ssGeH2')],
    "MINsssGeH": ["Minimum of atom-type E-State >GeH-", AtomTypeEState('min', 'sssGeH')],
    "MINssssGe": ["Minimum of atom-type E-State >Ge<", AtomTypeEState('min', 'ssssGe')],
    "MINsAsH2": ["Minimum of atom-type E-State -AsH2", AtomTypeEState('min', 'sAsH2')],
    "MINssAsH": ["Minimum of atom-type E-State -AsH-", AtomTypeEState('min', 'ssAsH')],
    "MINsssAs": ["Minimum of atom-type E-State >As-", AtomTypeEState('min', 'sssAs')],
    "MINsssdAs": ["Minimum of atom-type E-State >As-=", AtomTypeEState('min', 'sssdAs')],
    "MINsssssAs": ["Minimum of atom-type E-State #As<", AtomTypeEState('min', 'sssssAs')],
    "MINsSeH": ["Minimum of atom-type E-State -SeH", AtomTypeEState('min', 'sSeH')],
    "MINdSe": ["Minimum of atom-type E-State =Se", AtomTypeEState('min', 'dSe')],
    "MINssSe": ["Minimum of atom-type E-State -Se-", AtomTypeEState('min', 'ssSe')],
    "MINaaSe": ["Minimum of atom-type E-State :Se:", AtomTypeEState('min', 'aaSe')],
    "MINdssSe": ["Minimum of atom-type E-State =Se<", AtomTypeEState('min', 'dssSe')],
    "MINddssSe": ["Minimum of atom-type E-State =-Se-=", AtomTypeEState('min', 'ddssSe')],
    "MINsBr": ["Minimum of atom-type E-State -Br", AtomTypeEState('min', 'sBr')],
    "MINsSnH3": ["Minimum of atom-type E-State -SnH3", AtomTypeEState('min', 'sSnH3')],
    "MINssSnH2": ["Minimum of atom-type E-State -SnH2-", AtomTypeEState('min', 'ssSnH2')],
    "MINsssSnH": ["Minimum of atom-type E-State >SnH-", AtomTypeEState('min', 'sssSnH')],
    "MINssssSn": ["Minimum of atom-type E-State >Sn<", AtomTypeEState('min', 'ssssSn')],
    "MINsI": ["Minimum of atom-type E-State -I", AtomTypeEState('min', 'sI')],
    "MINsPbH3": ["Minimum of atom-type E-State -PbH3", AtomTypeEState('min', 'sPbH3')],
    "MINssPbH2": ["Minimum of atom-type E-State -PbH2-", AtomTypeEState('min', 'ssPbH2')],
    "MINsssPbH": ["Minimum of atom-type E-State >PbH-", AtomTypeEState('min', 'sssPbH')],
    "MINssssPb": ["Minimum of atom-type E-State >Pb<", AtomTypeEState('min', 'ssssPb')],



}

desc_fingerprint = {

}

desc_misc = {

}


desc_total = {
    "Composition": desc_composition,
    "Shape": desc_shape,
    "Charge": desc_electronic,

}
