from node_editor.node.mol_descriptors.functions import *

# Code / Description / Main function

# Constitutional descriptors: composition
desc_composition = {
    "aMW": ["Average molecular weight", MW('a')],
    "eMW": ["Exact molecular weight", MW('e')],
    "hMW": ["Average molecular weight excluding hydrogens", MW('h')],
    "nAtom": ["Number of atoms", AtmCount('Atom')],
    "nhAtom": ["Number of non-hydrogen atoms", AtmCount('HeavyAtom')],
    "nHAtoms": ["Number of heteroatoms", AtmCount('Hetero')],
    "nH": ["Number of H atoms", AtmCount('H')],
    "nB": ["Number of B atoms", AtmCount('B')],
    "nC": ["Number of C atoms", AtmCount('C')],
    "nN": ["Number of N atoms", AtmCount('N')],
    "nO": ["Number of O atoms", AtmCount('O')],
    "nS": ["Number of S atoms", AtmCount('S')],
    "nP": ["Number of P atoms", AtmCount('P')],
    "nF": ["Number of F atoms", AtmCount('F')],
    "nCl": ["Number of Cl atoms", AtmCount('Cl')],
    "nBr": ["Number of Br atoms", AtmCount('Br')],
    "nI": ["Number of I atoms", AtmCount('I')],
    "nX": ["Number of halogen atoms", AtmCount('X')],
    "nNHOH": ["Number of NHs or OHs", AtmCount('NHOH')],
    "nNO": ["Number of N and O atoms", AtmCount('NO')],
    "nHdonors": ["Number of hydrogen bond donors", AtmCount('Hdonnors')],
    "nHacceptors": ["Number of hydrogen bond acceptors", AtmCount('Hacceptors')],
    "nValelec": ["Number of valence electrons", ElecCount('Valence')],
    "nRadielec": ["Number of radical electrons", ElecCount('Radical')],
}

# Topological descriptors: connectivity
desc_connectivity = {
    "nBonds": ["Number of bonds", Calculator(BondCount.BondCount('any', False)), None],
    "nBondsO": ["Number of bonds between heavy atoms", Calculator(BondCount.BondCount('heavy', False)), None],
    "nBondsS": ["Number of single bonds", Calculator(BondCount.BondCount('single', False)), None],
    "nBondsD": ["Number of double bonds", Calculator(BondCount.BondCount('double', False)), None],
    "nBondsT": ["Number of triple bonds", Calculator(BondCount.BondCount('triple', False)), None],
    "nBondsM": ["Number of multiple bonds", Calculator(BondCount.BondCount('multiple', False)), None],
    "nBondsKS": ["Number of single bonds in kekulized strucutre", Calculator(BondCount.BondCount('single', True)), None],
    "nBondsKD": ["Number of double bonds in kekulized structure", Calculator(BondCount.BondCount('double', True)), None],
    "nRots": ["Number of rotatable bonds", Lipinski.NumRotatableBonds, Calculator(RotatableBond.RotatableBondsCount)],
    "nRotRatio": ["Rotatable bonds ratio", Calculator(RotatableBond.RotatableBondsRatio), None],
    "nAmides": ["Number of amide bonds", Lipinski.NumAmideBonds, None],
    "nArAtoms": ["Number of aromatic atoms", Calculator(Aromatic.AromaticAtomsCount), None],
    "nArBonds": ["Number of aromatic bonds", Calculator(Aromatic.AromaticBondsCount), Calculator(BondCount.BondCount('aromatic', False))],
    "nSAtoms": ["Number of spiro atoms", Lipinski.NumSpiroAtoms, Calculator(AtomCount.AtomCount('Spiro'))],
    "nBAtoms": ["Number of bridgehead atoms", Lipinski.NumBridgeheadAtoms, Calculator(AtomCount.AtomCount('Bridgehead'))],
    
    "nRings": ["Number of rings", Lipinski.RingCount, Calculator(RingCount.RingCount(None,False,False,None,None))],
    "n3Rings": ["Number of 3-membered rings", Calculator(RingCount.RingCount(3,False,False,None,None)), None],
    "n4Rings": ["Number of 4-membered rings", Calculator(RingCount.RingCount(4,False,False,None,None)), None],
    "n5Rings": ["Number of 5-membered rings", Calculator(RingCount.RingCount(5,False,False,None,None)), None],
    "n6Rings": ["Number of 5-membered rings", Calculator(RingCount.RingCount(6,False,False,None,None)), None],
    "n7Rings": ["Number of 5-membered rings", Calculator(RingCount.RingCount(7,False,False,None,None)), None],
    "n8Rings": ["Number of 5-membered rings", Calculator(RingCount.RingCount(8,False,False,None,None)), None],
    "n9Rings": ["Number of 5-membered rings", Calculator(RingCount.RingCount(9,False,False,None,None)), None],
    "n10Rings": ["Number of 5-membered rings", Calculator(RingCount.RingCount(10,False,False,None,None)), None],
    "n11Rings": ["Number of 5-membered rings", Calculator(RingCount.RingCount(11,False,False,None,None)), None],
    "n12Rings": ["Number of 5-membered rings", Calculator(RingCount.RingCount(12,False,False,None,None)), None],
    "nG3Rings": ["Number of rings with 3 or more atoms", Calculator(RingCount.RingCount(3,True,False,None,None)), None],
    "nG4Rings": ["Number of rings with 4 or more atoms", Calculator(RingCount.RingCount(4,True,False,None,None)), None],
    "nG5Rings": ["Number of rings with 5 or more atoms", Calculator(RingCount.RingCount(5,True,False,None,None)), None],
    "nG6Rings": ["Number of rings with 6 or more atoms", Calculator(RingCount.RingCount(6,True,False,None,None)), None],
    "nG7Rings": ["Number of rings with 7 or more atoms", Calculator(RingCount.RingCount(7,True,False,None,None)), None],
    "nG8Rings": ["Number of rings with 8 or more atoms", Calculator(RingCount.RingCount(8,True,False,None,None)), None],
    "nG9Rings": ["Number of rings with 9 or more atoms", Calculator(RingCount.RingCount(9,True,False,None,None)), None],
    "nG10Rings": ["Number of rings with 10 or more atoms", Calculator(RingCount.RingCount(10,True,False,None,None)), None],
    "nG11Rings": ["Number of rings with 11 or more atoms", Calculator(RingCount.RingCount(11,True,False,None,None)), None],
    "nG12Rings": ["Number of rings with 12 or more atoms", Calculator(RingCount.RingCount(12,True,False,None,None)), None],
    "nHRings": ["Number of hetero rings", Calculator(RingCount.RingCount(None,False,False,None,True)), None],
    "n3HRings": ["Number of hetero 3-membered rings", Calculator(RingCount.RingCount(3,False,False,None,True)), None],
    "n4HRings": ["Number of hetero 4-membered rings", Calculator(RingCount.RingCount(4,False,False,None,True)), None],
    "n5HRings": ["Number of hetero 5-membered rings", Calculator(RingCount.RingCount(5,False,False,None,True)), None],
    "n6HRings": ["Number of hetero 6-membered rings", Calculator(RingCount.RingCount(6,False,False,None,True)), None],
    "n7HRings": ["Number of hetero 7-membered rings", Calculator(RingCount.RingCount(7,False,False,None,True)), None],
    "n8HRings": ["Number of hetero 8-membered rings", Calculator(RingCount.RingCount(8,False,False,None,True)), None],
    "n9HRings": ["Number of hetero 9-membered rings", Calculator(RingCount.RingCount(9,False,False,None,True)), None],
    "n10HRings": ["Number of hetero 10-membered rings", Calculator(RingCount.RingCount(10,False,False,None,True)), None],
    "n11HRings": ["Number of hetero 11-membered rings", Calculator(RingCount.RingCount(11,False,False,None,True)), None],
    "n12HRings": ["Number of hetero 12-membered rings", Calculator(RingCount.RingCount(12,False,False,None,True)), None],
    "nG3HRings": ["Number of heetero rings with 3 or more atoms", Calculator(RingCount.RingCount(3,True,False,None,True)), None],
    "nG4HRings": ["Number of heetero rings with 4 or more atoms", Calculator(RingCount.RingCount(4,True,False,None,True)), None],
    "nG5HRings": ["Number of heetero rings with 5 or more atoms", Calculator(RingCount.RingCount(5,True,False,None,True)), None],
    "nG6HRings": ["Number of heetero rings with 6 or more atoms", Calculator(RingCount.RingCount(6,True,False,None,True)), None],
    "nG7HRings": ["Number of heetero rings with 7 or more atoms", Calculator(RingCount.RingCount(7,True,False,None,True)), None],
    "nG8HRings": ["Number of heetero rings with 8 or more atoms", Calculator(RingCount.RingCount(8,True,False,None,True)), None],
    "nG9HRings": ["Number of heetero rings with 9 or more atoms", Calculator(RingCount.RingCount(9,True,False,None,True)), None],
    "nG10HRings": ["Number of heetero rings with 10 or more atoms", Calculator(RingCount.RingCount(10,True,False,None,True)), None],
    "nG11HRings": ["Number of heetero rings with 11 or more atoms", Calculator(RingCount.RingCount(11,True,False,None,True)), None],
    "nG12HRings": ["Number of heetero rings with 12 or more atoms", Calculator(RingCount.RingCount(12,True,False,None,True)), None],
    "nArRings": ["Number of aromatic rings", Lipinski.NumAromaticRings, Calculator(RingCount.RingCount(None,False,False,True,None))],
    "n3ArRings": ["Number of aromatic 3-membered rings", Calculator(RingCount.RingCount(3,False,False,True,None)), None],
    "n4ArRings": ["Number of aromatic 4-membered rings", Calculator(RingCount.RingCount(4,False,False,True,None)), None],
    "n5ArRings": ["Number of aromatic 5-membered rings", Calculator(RingCount.RingCount(5,False,False,True,None)), None],
    "n6ArRings": ["Number of aromatic 6-membered rings", Calculator(RingCount.RingCount(6,False,False,True,None)), None],
    "n7ArRings": ["Number of aromatic 7-membered rings", Calculator(RingCount.RingCount(7,False,False,True,None)), None],
    "n8ArRings": ["Number of aromatic 8-membered rings", Calculator(RingCount.RingCount(8,False,False,True,None)), None],
    "n9ArRings": ["Number of aromatic 9-membered rings", Calculator(RingCount.RingCount(9,False,False,True,None)), None],
    "n10ArRings": ["Number of aromatic 10-membered rings", Calculator(RingCount.RingCount(10,False,False,True,None)), None],
    "n11ArRings": ["Number of aromatic 11-membered rings", Calculator(RingCount.RingCount(11,False,False,True,None)), None],
    "n12ArRings": ["Number of aromatic 12-membered rings", Calculator(RingCount.RingCount(12,False,False,True,None)), None],
    "nG3ArRings": ["Number of aromatic rings with 3 or more atoms", Calculator(RingCount.RingCount(3,True,False,True,None)), None],
    "nG4ArRings": ["Number of aromatic rings with 4 or more atoms", Calculator(RingCount.RingCount(4,True,False,True,None)), None],
    "nG5ArRings": ["Number of aromatic rings with 5 or more atoms", Calculator(RingCount.RingCount(5,True,False,True,None)), None],
    "nG6ArRings": ["Number of aromatic rings with 6 or more atoms", Calculator(RingCount.RingCount(6,True,False,True,None)), None],
    "nG7ArRings": ["Number of aromatic rings with 7 or more atoms", Calculator(RingCount.RingCount(7,True,False,True,None)), None],
    "nG8ArRings": ["Number of aromatic rings with 8 or more atoms", Calculator(RingCount.RingCount(8,True,False,True,None)), None],
    "nG9ArRings": ["Number of aromatic rings with 9 or more atoms", Calculator(RingCount.RingCount(9,True,False,True,None)), None],
    "nG10ArRings": ["Number of aromatic rings with 10 or more atoms", Calculator(RingCount.RingCount(10,True,False,True,None)), None],
    "nG11ArRings": ["Number of aromatic rings with 11 or more atoms", Calculator(RingCount.RingCount(11,True,False,True,None)), None],
    "nG12ArRings": ["Number of aromatic rings with 12 or more atoms", Calculator(RingCount.RingCount(12,True,False,True,None)), None],
    #TODO: add more ring descriptors

    "BalabanJ": ["Balaban's J index", GraphDescriptors.BalabanJ, Calculator(BalabanJ.BalabanJ)],
    "BertzCT": ["Bertz CT", GraphDescriptors.BertzCT, Calculator(BertzCT.BertzCT)],
    "TPSA": ["Topological polar surface area", TPSA()],
    
    #TODO: BCUT descriptors
    #TODO: IPC descriptors

    #TODO: Chi descriptors

    "ETA_alpha": ["ETA core count", EtaCoreCount(False,False)],
    "ETA_alpha_avg": ["ETA core count averaged by number of heavy atoms", EtaCoreCount(True,False)],
    "ETA_shape_p": ["ETA shape index type p", EtaShapeIndex('p')],
    "ETA_shape_y": ["ETA shape index type y", EtaShapeIndex('y')],
    "ETA_shape_x": ["ETA shape index type x", EtaShapeIndex('x')],
    "ETA_beta": ["ETA VEM count", EtaVEMCount('',False)],
    "ETA_beta_avg": ["ETA VEM count averaged by number of heavy atoms", EtaVEMCount('',True)],
    "ETA_beta_s": ["ETA VEM count type s", EtaVEMCount('s',False)],
    "ETA_beta_s_avg": ["ETA VEM count type s averaged by number of heavy atoms", EtaVEMCount('s',True)],
    "ETA_beta_ns": ["ETA VEM count type ns", EtaVEMCount('ns',False)],
    "ETA_beta_ns_avg": ["ETA VEM count type ns averaged by number of heavy atoms", EtaVEMCount('ns',True)],
    "ETA_beta_ns_d": ["ETA VEM count type ns_d", EtaVEMCount('ns_d',False)],
    "ETA_beta_ns_d_avg": ["ETA VEM count type ns_d averaged by number of heavy atoms", EtaVEMCount('ns_d',True)],
    "ETA_eta": ["ETA composite index", EtaCompositeIndex(False,False,False)],
    "ETA_eta_avg": ["ETA composite index averaged by number of heavy atoms", EtaCompositeIndex(False,False,True)],
    "ETA_eta_L": ["ETA composite index use local eta", EtaCompositeIndex(False,True,False)],
    "ETA_eta_L_avg": ["ETA composite index use local eta averaged by number of heavy atoms", EtaCompositeIndex(False,True,True)],
    "ETA_eta_R": ["ETA composite index use reference alkane", EtaCompositeIndex(True,False,False)],
    "ETA_eta_R_avg": ["ETA composite index use reference alkane averaged by number of heavy atoms", EtaCompositeIndex(True,False,True)],
    "ETA_eta_RL": ["ETA composite index use reference alkane and local eta", EtaCompositeIndex(True,True,False)],
    "ETA_eta_RL_avg": ["ETA composite index use reference alkane and local eta averaged by number of heavy atoms", EtaCompositeIndex(True,True,True)],
    "ETA_eta_F": ["ETA functionality index", EtaFunctionalityIndex(False,False)],
    "ETA_eta_F_avg": ["ETA functionality index averaged by number of heavy atoms", EtaFunctionalityIndex(False,True)],
    "ETA_eta_FL": ["ETA functionality index use local eta", EtaFunctionalityIndex(True,False)],
    "ETA_eta_FL_avg": ["ETA functionality index use local eta averaged by number of heavy atoms", EtaFunctionalityIndex(True,True)],
    "ETA_eta_B": ["ETA branching index", EtaBranchingIndex(False,False)],
    "ETA_eta_B_avg": ["ETA branching index averaged by number of heavy atoms", EtaBranchingIndex(False,True)],
    "ETA_eta_BR": ["ETA branching index use ring count", EtaBranchingIndex(True,False)],
    "ETA_eta_BR_avg": ["ETA branching index use ring count averaged by number of heavy atoms", EtaBranchingIndex(True,True)],
    "ETA_dAlpha_A": ["ETA delta alpha type A", EtaDeltaAlpha('A')],
    "ETA_dAlpha_B": ["ETA delta alpha type B", EtaDeltaAlpha('B')],
    "ETA_epsilon1": ["ETA epsilon all atoms", EtaEpsilon(1)],
    "ETA_epsilon2": ["ETA epsilon heavy atoms", EtaEpsilon(2)],
    "ETA_epsilon3": ["ETA epsilon all atoms of reference alkane", EtaEpsilon(3)],
    "ETA_epsilon4": ["ETA epsilon all atoms of saturated carbon skeleton", EtaEpsilon(4)],
    "ETA_epsilon5": ["ETA epsilon hydrogens bond to hetero atoms", EtaEpsilon(5)],
    "ETA_dEpsilon_A": ["ETA delta epsilon type A", EtaDeltaEpsilon('A')],
    "ETA_dEpsilon_B": ["ETA delta epsilon type B", EtaDeltaEpsilon('B')],
    "ETA_dEpsilon_C": ["ETA delta epsilon type C", EtaDeltaEpsilon('C')],
    "ETA_dEpsilon_D": ["ETA delta epsilon type D", EtaDeltaEpsilon('D')],
    "ETA_dBeta": ["ETA delta beta", EtaDeltaBeta(False)],
    "ETA_dBeta_avg": ["ETA delta beta averaged by number of heavy atoms", EtaDeltaBeta(True)],
    "ETA_Psi": ["ETA psi", EtaPsi()],
    "ETA_dPsi_A": ["ETA delta psi type A", EtaDeltaPsi('A')],
    "ETA_dPsi_B": ["ETA delta psi type B", EtaDeltaPsi('B')],

}

desc_shape = {
    "LabuteASA": ["Labute's approximate surface area", MolSurf.LabuteASA, Calculator(MoeType.LabuteASA)],
    "PEOE_VSA1": ["MOE charge VSA 1", MolSurf.PEOE_VSA1, Calculator(MoeType.PEOE_VSA(1))],
    "PEOE_VSA2": ["MOE charge VSA 2", MolSurf.PEOE_VSA2, Calculator(MoeType.PEOE_VSA(2))],
    "PEOE_VSA3": ["MOE charge VSA 3", MolSurf.PEOE_VSA3, Calculator(MoeType.PEOE_VSA(3))],
    "PEOE_VSA4": ["MOE charge VSA 4", MolSurf.PEOE_VSA4, Calculator(MoeType.PEOE_VSA(4))],
    "PEOE_VSA5": ["MOE charge VSA 5", MolSurf.PEOE_VSA5, Calculator(MoeType.PEOE_VSA(5))],
    "PEOE_VSA6": ["MOE charge VSA 6", MolSurf.PEOE_VSA6, Calculator(MoeType.PEOE_VSA(6))],
    "PEOE_VSA7": ["MOE charge VSA 7", MolSurf.PEOE_VSA7, Calculator(MoeType.PEOE_VSA(7))],
    "PEOE_VSA8": ["MOE charge VSA 8", MolSurf.PEOE_VSA8, Calculator(MoeType.PEOE_VSA(8))],
    "PEOE_VSA9": ["MOE charge VSA 9", MolSurf.PEOE_VSA9, Calculator(MoeType.PEOE_VSA(9))],
    "PEOE_VSA10": ["MOE charge VSA 10", MolSurf.PEOE_VSA10, Calculator(MoeType.PEOE_VSA(10))],
    "PEOE_VSA11": ["MOE charge VSA 11", MolSurf.PEOE_VSA11, Calculator(MoeType.PEOE_VSA(11))],
    "PEOE_VSA12": ["MOE charge VSA 12", MolSurf.PEOE_VSA12, Calculator(MoeType.PEOE_VSA(12))],
    "PEOE_VSA13": ["MOE charge VSA 13", MolSurf.PEOE_VSA13, Calculator(MoeType.PEOE_VSA(13))],
    "PEOE_VSA14": ["MOE charge VSA 14", MolSurf.PEOE_VSA14, Calculator(MoeType.PEOE_VSA(14))],
    "SMR_VSA1": ["MOE MR VSA 1", MolSurf.SMR_VSA1, Calculator(MoeType.SMR_VSA(1))],
    "SMR_VSA2": ["MOE MR VSA 2", MolSurf.SMR_VSA2, Calculator(MoeType.SMR_VSA(2))],
    "SMR_VSA3": ["MOE MR VSA 3", MolSurf.SMR_VSA3, Calculator(MoeType.SMR_VSA(3))],
    "SMR_VSA4": ["MOE MR VSA 4", MolSurf.SMR_VSA4, Calculator(MoeType.SMR_VSA(4))],
    "SMR_VSA5": ["MOE MR VSA 5", MolSurf.SMR_VSA5, Calculator(MoeType.SMR_VSA(5))],
    "SMR_VSA6": ["MOE MR VSA 6", MolSurf.SMR_VSA6, Calculator(MoeType.SMR_VSA(6))],
    "SMR_VSA7": ["MOE MR VSA 7", MolSurf.SMR_VSA7, Calculator(MoeType.SMR_VSA(7))],
    "SMR_VSA8": ["MOE MR VSA 8", MolSurf.SMR_VSA8, Calculator(MoeType.SMR_VSA(8))],
    "SMR_VSA9": ["MOE MR VSA 9", MolSurf.SMR_VSA9, Calculator(MoeType.SMR_VSA(9))],
    "SMR_VSA10": ["MOE MR VSA 10", MolSurf.SMR_VSA10, Calculator(MoeType.SMR_VSA(10))],
    "SlogP_VSA1": ["MOE logP VSA 1", MolSurf.SlogP_VSA1, Calculator(MoeType.SlogP_VSA(1))],
    "SlogP_VSA2": ["MOE logP VSA 2", MolSurf.SlogP_VSA2, Calculator(MoeType.SlogP_VSA(2))],
    "SlogP_VSA3": ["MOE logP VSA 3", MolSurf.SlogP_VSA3, Calculator(MoeType.SlogP_VSA(3))],
    "SlogP_VSA4": ["MOE logP VSA 4", MolSurf.SlogP_VSA4, Calculator(MoeType.SlogP_VSA(4))],
    "SlogP_VSA5": ["MOE logP VSA 5", MolSurf.SlogP_VSA5, Calculator(MoeType.SlogP_VSA(5))],
    "SlogP_VSA6": ["MOE logP VSA 6", MolSurf.SlogP_VSA6, Calculator(MoeType.SlogP_VSA(6))],
    "SlogP_VSA7": ["MOE logP VSA 7", MolSurf.SlogP_VSA7, Calculator(MoeType.SlogP_VSA(7))],
    "SlogP_VSA8": ["MOE logP VSA 8", MolSurf.SlogP_VSA8, Calculator(MoeType.SlogP_VSA(8))],
    "SlogP_VSA9": ["MOE logP VSA 9", MolSurf.SlogP_VSA9, Calculator(MoeType.SlogP_VSA(9))],
    "SlogP_VSA10": ["MOE logP VSA 10", MolSurf.SlogP_VSA10, Calculator(MoeType.SlogP_VSA(10))],
    "SlogP_VSA11": ["MOE logP VSA 11", MolSurf.SlogP_VSA11, Calculator(MoeType.SlogP_VSA(11))],
    "SlogP_VSA12": ["MOE logP VSA 12", MolSurf.SlogP_VSA12, Calculator(MoeType.SlogP_VSA(12))],
    "EState_VSA1": ["MOE EState VSA 1", EState.EState_VSA.EState_VSA1, Calculator(MoeType.EState_VSA(1))],
    "EState_VSA2": ["MOE EState VSA 2", EState.EState_VSA.EState_VSA2, Calculator(MoeType.EState_VSA(2))],
    "EState_VSA3": ["MOE EState VSA 3", EState.EState_VSA.EState_VSA3, Calculator(MoeType.EState_VSA(3))],
    "EState_VSA4": ["MOE EState VSA 4", EState.EState_VSA.EState_VSA4, Calculator(MoeType.EState_VSA(4))],
    "EState_VSA5": ["MOE EState VSA 5", EState.EState_VSA.EState_VSA5, Calculator(MoeType.EState_VSA(5))],
    "EState_VSA6": ["MOE EState VSA 6", EState.EState_VSA.EState_VSA6, Calculator(MoeType.EState_VSA(6))],
    "EState_VSA7": ["MOE EState VSA 7", EState.EState_VSA.EState_VSA7, Calculator(MoeType.EState_VSA(7))],
    "EState_VSA8": ["MOE EState VSA 8", EState.EState_VSA.EState_VSA8, Calculator(MoeType.EState_VSA(8))],
    "EState_VSA9": ["MOE EState VSA 9", EState.EState_VSA.EState_VSA9, Calculator(MoeType.EState_VSA(9))],
    "EState_VSA10": ["MOE EState VSA 10", EState.EState_VSA.EState_VSA10, Calculator(MoeType.EState_VSA(10))],
    "EState_VSA11": ["MOE EState VSA 11", EState.EState_VSA.EState_VSA11, Calculator(MoeType.EState_VSA(11))],
    "VSA_EState1": ["MOE VSA EState 1", EState.EState_VSA.VSA_EState1, Calculator(MoeType.VSA_EState(1))],
    "VSA_EState2": ["MOE VSA EState 2", EState.EState_VSA.VSA_EState2, Calculator(MoeType.VSA_EState(2))],
    "VSA_EState3": ["MOE VSA EState 3", EState.EState_VSA.VSA_EState3, Calculator(MoeType.VSA_EState(3))],
    "VSA_EState4": ["MOE VSA EState 4", EState.EState_VSA.VSA_EState4, Calculator(MoeType.VSA_EState(4))],
    "VSA_EState5": ["MOE VSA EState 5", EState.EState_VSA.VSA_EState5, Calculator(MoeType.VSA_EState(5))],
    "VSA_EState6": ["MOE VSA EState 6", EState.EState_VSA.VSA_EState6, Calculator(MoeType.VSA_EState(6))],
    "VSA_EState7": ["MOE VSA EState 7", EState.EState_VSA.VSA_EState7, Calculator(MoeType.VSA_EState(7))],
    "VSA_EState8": ["MOE VSA EState 8", EState.EState_VSA.VSA_EState8, Calculator(MoeType.VSA_EState(8))],
    "VSA_EState9": ["MOE VSA EState 9", EState.EState_VSA.VSA_EState9, Calculator(MoeType.VSA_EState(9))],
    "VSA_EState10": ["MOE VSA EState 10", EState.EState_VSA.VSA_EState10, Calculator(MoeType.VSA_EState(10))],

    "McGowan": ["McGowan volume", Calculator(McGowanVolume.McGowanVolume), None],
    "Radius": ["Radius of gyration", Radius()],
    "Diameter": ["Diameter of gyration", Diameter()],
    "TopoShapeIndex": ["Topological shape index", TopologicalShapeIndex()],
    "PetitjeanIndex": ["Petitjean index", PetitjeanIndex()],
    "VABC": ["Van der Waals volume (ABC)", VABC()],
    "Asphericity": ["Molecular asphericity", Asphericity()],
    "Eccentricity": ["Molecular eccentricity", Eccentricity()],
    "InertialShapeFactor": ["Inertial shape factor", InertialShapeFactor()],
    "NPR1": ["Normalized principal moments ratio 1 (=I1/I3)", NPR(1)],
    "NPR2": ["Normalized principal moments ratio 2 (=I2/I3)", NPR(2)],
    "PBF": ["Plane of best fit", PBF()],
    "PMI1": ["First (smallest) principal moment of inertia", PMI(1)],
    "PMI2": ["Second principal moment of inertia", PMI(2)],
    "PMI3": ["Third principal moment of inertia", PMI(3)],
    "SpherocityIndex": ["Molecular spherocity index", SpherocityIndex()],
    "Kappa1": ["Kappa shape index 1", Kappa(1)],
    "Kappa2": ["Kappa shape index 2", Kappa(2)],
    "Kappa3": ["Kappa shape index 3", Kappa(3)],

    #TODO: Carbon type
}

desc_electronic = {

}

desc_fingerprint = {

}

desc_misc = {

}


desc_total = {
    "Composition": desc_composition,
    "Shape": desc_shape
}
